### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by yvendruscolo** [djblue/portal#26]
With the ubiquity of YAML format, it would be useful to have a direct support for it from the cli.

I have started an experiment on [a fork](https://github.com/yvendruscolo/portal), which seems to work fine, but it could use some further development.

**Comment by djblue** [comment]
Hi @yvendruscolo, I think adding YAML support is a great idea! I do think we should prefer [clj-yaml](https://github.com/clj-commons/clj-yaml) since it would make [babashka](https://github.com/borkdude/babashka) support trivial.

Also, I think it should be optional support, so we should expect users to include clj-yaml in their deps instead of mandating it for all users. Using [`resolve`](https://clojuredocs.org/clojure.core/resolve) should help do the trick.

**Comment by yvendruscolo** [comment]
great idea, will check it out!

**Comment by djblue** [comment]
Released as part of `0.7.0`
